### ISSUE TITLE
`mix ecto.load` does not work when a port is configured

### ISSUE THREAD

**Issue by hkrutzer** [plausible/ecto_ch#107]
When explicitly configuring a `port` for the adapter, this port will also be used when running `mix ecto.load`.

However, as this command uses the command line client, the command line client will now try to connect over the HTTP port, which will fail.

**Comment by ruslandoga** [comment]
Oh, right. I'm not sure what we should do in that case. Should we rewrite 8123 to 9000? Or should we print a warning?

**Comment by hkrutzer** [comment]
I don't think the configured port can ever be used, as it should always be the HTTP(S) port. But there's also no way to configure the port as a parameter of the `ecto.load` command, so if you want to use e.g. port 9001, it will have to have that value only for `ecto.load`, using an ENV var or something..

Perhaps the following is best:
- Warn if `port` is configured at all and `ecto.load` runs
- (Optional) add a custom option like `native_port:` to the adapter settings, which the warning will mention
- (Optional) automatically rewrite 8123 to 9000 (this is risky, because someone might not be aware the command needs the native port and may have something else running there)

**Comment by ruslandoga** [comment]
I think we can rewrite `ecto.load` to use our http client instead of `clickhouse-client` binary. I was initially against that idea since `Ecto.Adapters.Postgres` used `psql` and `pg_dump` but it doesn't seem like using `clickhouse-client` would work for us.

**Comment by hkrutzer** [comment]
That also seems like a good option. It seems all the adapters that have a dump/load function use the native client (e.g. SQLite3 also does this), but I'm not sure why.

**Comment by ruslandoga** [comment]
@hkrutzer 👋

I've started a PR https://github.com/plausible/ecto_ch/pull/111 for `structure_load` over http

**Comment by hkrutzer** [comment]
Works fine for me!
