### ISSUE TITLE
drop hints support

### ISSUE THREAD

**Issue by ruslandoga** [plausible/ecto_ch#125]
It doesn't seem like ClickHouse supports hints. In Plausible `query.hints` are [used](https://github.com/search?q=repo%3Aplausible%2Fanalytics+hints+language%3AElixir&type=code&l=Elixir) as a workaround to pass the [`SAMPLE` clause.](https://clickhouse.com/docs/en/sql-reference/statements/select/sample)

Maybe it can be similar to [`input/1`](https://hexdocs.pm/ecto_ch/Ecto.Adapters.ClickHouse.API.html#input/1) helper function:

```elixir
q = from t in sample("table", 0.1), select: count(t.id) * 10
# select count(t.id) * 10 from table t sample 0.1
```

**Comment by hkrutzer** [comment]
I use them to add `FINAL` as I wrote here https://github.com/plausible/ecto_ch/pull/103/files (which I will update soon :) )

**Comment by ruslandoga** [comment]
`FINAL` is not a hint. It seems like ClickHouse is using settings in place of hints.

**Comment by hkrutzer** [comment]
Indeed it's not a hint but it seems to be the only way to pass it into that query from Ecto. I don't think Ecto supports a settings clause?

**Comment by ruslandoga** [comment]
It doesn't have to go into the Ecto query, settings can be passed separately from the query.

**Comment by Zarathustra2** [comment]
I think `final` still has some issues because it cannot move always the `where` clause to `prewhere`. See https://github.com/ClickHouse/ClickHouse/issues/31411

So I would advise to not use/promote the usage of `final` too much.

**Comment by hkrutzer** [comment]
Some queries cannot be performed without FINAL but I think that is tangential to this issue.

**Comment by Zarathustra2** [comment]
Really? Do you have an example? I am curious because I cannot think of an example maybe because I never encountered such a situation

**Comment by hkrutzer** [comment]
When using an `AggregatingMergeTree` and you need the merged result for example

**Comment by hkrutzer** [comment]
I don't use it like that, I merge several partial records into one final record, like this (simplified):

```sql
`id` FixedString(26),
`started_at` DateTime('UTC') MATERIALIZED ULIDStringToDateTime(id),
`disconnected_at` SimpleAggregateFunction(max, DateTime('UTC')),
`user_responded_at` SimpleAggregateFunction(max, DateTime('UTC')),
`properties` SimpleAggregateFunction(groupArrayArray, Array(String))
```

Additional properties (in the properties column) can be added to the record at any time, and the `disconnected_at` and `user_responded_at` are inserted later as well. They are eventually merged based on the ID column.

**Comment by Zarathustra2** [comment]
But can't you just do ```sql
select id, started_at, max(disconnected_at) as disconnected_at, max(user_responded_at) as user_responded_at, groupArrayArray(properties) as properties from <table> group by id, started_at
```

Maybe I am not really following. Still I don't think there is any query which you can only run with final and not as a group by + aggregation.

**Comment by hkrutzer** [comment]
I don't know if I can, but why would I do it that way? That is a way longer query.

**Comment by Zarathustra2** [comment]
It depends on your use case. If you have a small dataset final should be fine. If you have a larger dataset final should be avoided. If you don't run into performance issues or don't care about speed then final is also fine.

**Comment by hkrutzer** [comment]
If I query with a group by, I get
```
10 rows in set. Elapsed: 6.001 sec. Processed 33.86 million rows, 802.51 MB (5.64 million rows/s., 133.73 MB/s.)
```

and with the `FINAL` modifier:

```
10 rows in set. Elapsed: 0.584 sec. Processed 94.00 thousand rows, 110.76 KB (160.89 thousand rows/s., 189.56 KB/s.)
```

**Comment by Zarathustra2** [comment]
I mean 0.584 isn't bad but also I dont see the full query & table so cannot say whether the query without final is performant or not

**Comment by hkrutzer** [comment]
If you say so. I will stop derailing this issue, I think I've made a clear case for `FINAL`.

**Comment by Zarathustra2** [comment]
The case is not clear because I don't see the table definition and the queries you used that result in that huge performance diff

**Comment by ruslandoga** [comment]
Closing this for now as Ecto `:hints` field in `from` and `join` seems like the easiest workaround for SAMPLE, special JOINS, and some other clauses in ClickHouse.
