### ISSUE TITLE
`Ecto.Type` with a Clickhouse type

### ISSUE THREAD

**Issue by hkrutzer** [plausible/ecto_ch#127]
I'm looking to do stuff like this:

```
field :name, Ch, type: "Nullable(Ecto.UUID)"
```

and use fields like:
```
field(:id, Ch, type: "FixedString(26)")
```

with [ecto-ulid](https://github.com/woylie/ecto_ulid). Is there a way to do this?

**Comment by ruslandoga** [comment]
I think you might be able to use a custom Ecto.Type type similar to https://github.com/plausible/ecto_ch/blob/752ca72090940f2836bbba0b054170a7367daf40/test/support/ecto_schemas.exs#L28-L35

**Comment by ruslandoga** [comment]
So I guess it'd be something like

```elixir
defmodule Ch.ULID do
  use Ecto.Type

  def type, do: Ecto.UUID
  def cast(value), do: Ecto.ULID.cast(value)
  def load(value), do: Ecto.ULID.load(value)
  def dump(value), do: Ecto.ULID.dump(value)
  def autogenerate, do: Ecto.ULID.autogenerate
end
```

But not that UUID is not the same as `FixedString(36)`

**Comment by hkrutzer** [comment]
Sorry I meant FixedString(26).

**Comment by ruslandoga** [comment]
@hkrutzer 👋

Can this issue be closed?

**Comment by hkrutzer** [comment]
Yes, I ended up just using a FixedString without the ULID type because I wasn't able to get it to work in a nice way.
