### ISSUE TITLE
Issue with Map with bool values

### ISSUE THREAD

**Issue by hkrutzer** [plausible/ecto_ch#128]
I am having an issue where I have a field like this:
```
    field(:bools, Ch,
      type: "SimpleAggregateFunction(groupArrayArray, Array(Map(String, UInt8)))"
    )
```

and I insert data like this: `[%{"foo"=> true}, %{"bar" => false}]`.
This causes an error:
```
{"is invalid",
              [
                type: {:parameterized, Ch,
                 {:simple_aggregate_function, "groupArrayArray",
                  {:array, {:map, :string, :u8}}}},
                validation: :cast
              ]}
```

`true` is of course not a UInt8 so I suspect that is what is causing the error.

But when I make it a `Bool`, I get

```
** (Ch.Error) Code: 117. DB::Exception: Type of 'bools' must be SimpleAggregateFunction(groupArrayArray, Array(Map(String, UInt8))), not SimpleAggregateFunction(groupArrayArray, Array(Map(String, Bool))): While executing BinaryRowInputFormat. (INCORRECT_DATA) (version 23.7.4.5 (official build))
```

Perhaps https://github.com/plausible/ecto_ch/pull/126 happens to address this? But I thought I'd make an issue anyway.

**Comment by ruslandoga** [comment]
No, #126 wouldn't change the internals of `Ch` Ecto type, it's mostly about queries that use `type/2` macro.

Can you please share more of your code? Ideally as a failing test case.
