### ISSUE TITLE
Some strings are displayed as binary

### ISSUE THREAD

**Issue by arrowcircle** [plausible/ecto_ch#158]
Hey! I have a problem displaying strings, some are displayed as binary.
I have definitions like:

```
field(:owner, Ch, type: "FixedString(100)")
```

and it displays something like `<<49, 50, 67, 90, 68, 69, 107, 57, 114, 78, 98, 88, 106, 85, 74, 77, 77, 55, 97, 72, 111, 85, 57, 112, 99, 54, 57, 84, 104, 68, 50, 51, 121, 83, 76, 116, 119, 66, 102, 105, 119, 56, 54, 49, 0, 0, 0, 0, 0, 0>>`

While some other strings are displayed properly.
Could you please tell how to fix this problem?

**Comment by ruslandoga** [comment]
@arrowcircle 

The binary is not displayed as text because it contains null bytes padding in the end to make it 100 bytes. To make them displayable you can use something like `String.trim_trailing`

```elixir
iex> fixed_string_100 = <<49, 50, 67, 90, 68, 69, 107, 57, 114, 78, 98, 88, 106, 85, 74, 77, 77, 55, 97, 72, 111, 85, 57, 112, 99, 54, 57, 84, 104, 68, 50, 51, 121, 83, 76, 116, 119, 66, 102, 105, 119, 56, 54, 49, 0, 0, 0, 0, 0, 0>>
<<49, 50, 67, 90, 68, 69, 107, 57, 114, 78, 98, 88, 106, 85, 74, 77, 77, 55, 97,
  72, 111, 85, 57, 112, 99, 54, 57, 84, 104, 68, 50, 51, 121, 83, 76, 116, 119,
  66, 102, 105, 119, 56, 54, 49, 0, 0, 0, 0, 0, 0>>
iex> String.trim_trailing fixed_string_100, <<0>>
"12CZDEk9rNbXjUJMM7aHoU9pc69ThD23ySLtwBfiw861"
```
or migrate to the `String` type.
