### ISSUE TITLE
support update statements

### ISSUE THREAD

**Issue by jaronoff97** [plausible/ecto_ch#169]
it would be great if this package supported Repo.update by using the correct clickhouse `ALTER TABLE` statement rather than erroring. Everything else has worked seamlessly, so this would be great :)

**Comment by ruslandoga** [comment]
I was thinking about adding a custom Repo.alter_update functions but then forgot. I'd like to reserve Repo.update for the actual UPDATE statements.

**Comment by jaronoff97** [comment]
Yeah! that'd be great :D thank you! For now, I changed to use a versioned insert approach to avoid doing any table alterations, but this would be great.

**Comment by ruslandoga** [comment]
I've added `Repo.alter_update_all` in https://github.com/plausible/ecto_ch/pull/172 and released it as v0.3.7.

**Comment by jaronoff97** [comment]
Thank you so much!! Unblocks a bunch of stuff for me. I appreciate the fast turn around and your work here!
