### ISSUE TITLE
invalid join qualifier `"ASOF INNER JOIN"`

### ISSUE THREAD

**Issue by JVMartyns** [plausible/ecto_ch#202]
Is there any way to use ASOF join currently?

Something like this
```elixir
MyTableOne
|> join(:asof_inner, [tb1], tb2 in MyTableTwo,
  on: tb1.created_at <= tb2.created_at
)
```
Or like this
```elixir
MyTableOne
|> join("ASOF INNER", [tb1], tb2 in MyTableTwo,
  on: tb1.created_at <= tb2.created_at
)
```

**Comment by ruslandoga** [comment]
👋 @JVMartyns 

Yes, please see these tests https://github.com/plausible/ecto_ch/blob/master/test/ecto/integration/clickhouse_joins_test.exs
