### ISSUE TITLE
Add clickhouse specific functions as macros

### ISSUE THREAD

**Issue by Zarathustra2** [plausible/ecto_ch#28]
Thoughts about adding clickhouse specific functions ( any, sumIf, anyLast, etc.) as macros?

We could create a new module `Ch.Query` which one could import to get access to those macros.

**Comment by ruslandoga** [comment]
I wonder if it can work better as a separate package.

Two reasons for this:

- other official adapters don't seem to define custom functions beyond what's in `Ecto.Query.API`
- supporting all custom functions feels like quite a bit of work, and supporting a subset might be unintuitive to users who want to use the functions we haven't added

**Comment by Zarathustra2** [comment]
I could do a separate package, think that is the best idea! Do you have any name suggestions? Then I could look into creating one. ( I have never created a elixir package before so that sounds fun to me! :) )

On a different note, have you thought about adding a description to this repo so that maybe others could find it easier + publishing it on hexpm ?

**Comment by ruslandoga** [comment]
Sorry, I don't have any naming suggestions...

> On a different note, have you thought about adding a description to this repo so that maybe others could find it easier + publishing it on hexpm ?

Yeah, that's WIP :) I'm preparing https://github.com/plausible/ch to be published first. And then chto. It would probably happen sometime next week.

**Comment by ruslandoga** [comment]
> On a different note, have you thought about adding a description to this repo so that maybe others could find it easier + publishing it on hexpm ?

Published as https://hex.pm/packages/ecto_ch
