### ISSUE TITLE
Ecto.Adapters.ClickHouse.structure_load: not implemented

### ISSUE THREAD

**Issue by Zarathustra2** [plausible/ecto_ch#37]
Can we support this? I am currently migrating my old clickhouse schema files over and would like to have my old schema in a structure.sql. 

Can we not just split on `;` and execute every query step by step with the caveat there is no option for a rollback and that it can fail while executing? I feel like this is reasonable for a load operation since one expects the structure.sql to only be loaded once or during ci jobs on clean fresh databases

**Comment by Zarathustra2** [comment]
I will look into this then soonish!

**Comment by Zarathustra2** [comment]
@ruslandoga I wanted to work on this. How do you set up your dev environement to run command line things such as `mix ecto.load`? 

Do you create a separate app and then just reference your local `ecto_ch` as dependency?

**Comment by ruslandoga** [comment]
I don't remember exactly what I did during development, I think I tested the callbacks directly: https://github.com/plausible/ecto_ch/blob/master/test/ecto/adapters/clickhouse/structure_test.exs, and once the tests pass did a manual test in a separate app (plausible/analytics).

**Comment by Zarathustra2** [comment]
Ah perfect, I am doing the same right now

**Comment by ruslandoga** [comment]
History shows that I already had "working" code when adding tests.

https://github.com/plausible/ecto_ch/pull/17/files

Maybe I used the dev repo: https://github.com/plausible/ecto_ch/blob/master/dev/repo.ex
