### ISSUE TITLE
Cannot rollback

### ISSUE THREAD

**Issue by Zarathustra2** [plausible/ecto_ch#47]
Running `mix ecto.rollback` results in
```
** (Ch.Error) Code: 36. DB::Exception: DELETE query is not supported for table test_database.schema_migrations. (BAD_ARGUMENTS) (version 23.1.6.42 (official build))

    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (chto 0.1.0) lib/ecto/adapters/clickhouse.ex:213: Ecto.Adapters.ClickHouse.execute/5
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:334: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:348: Ecto.Migrator.run_maybe_in_transaction/5
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I will debug this one

**Comment by ruslandoga** [comment]
`TinyLog` is used for `schema_migrations` table by default. And `TinyLog` doesn't allow `DELETE`.

**Comment by Zarathustra2** [comment]
ohhh, shouldn't we use https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree for migrations?

**Comment by ruslandoga** [comment]
Why?

**Comment by Zarathustra2** [comment]
So can delete on all versions of clickhouse? Aren't on < 23 clickhouse all deletes async? ( I am new to clickhouse but I thought that was the case)

**Comment by ruslandoga** [comment]
How would deletes happen for `CollapsingMergeTree`?

**Comment by Zarathustra2** [comment]
we would add a sign to the schema migations table and when checking if a migration has already been applied, we would run
`select ... from schem_migrations where id = <ID> group by ID having sum(sign) > 0`.

**Comment by ruslandoga** [comment]
I think we can make the default table engine configurable.

https://github.com/plausible/chto/blob/9bddd6273d23f1875693302bfbea1992047cdb22/lib/ecto/adapters/clickhouse/migration.ex#L19

would be `engine || Applicatin.get_env(:chto, :default_engine) || "TinyLog"`

**Comment by Zarathustra2** [comment]
the issue is what about users who are running production currently with `TinyLog`? We would have to add something to migrate that over, no?

**Comment by ruslandoga** [comment]
Production usually doesn't rollback. `TinyLog` would still stay the default engine so there is no need to migrate existing deployments.

**Comment by Zarathustra2** [comment]
true good point, I did not think about it

**Comment by cnkk** [comment]
@ruslandoga jfyi, we use the ReplicatedMergeTree engine for the schema_migrations table on prod.
