### ISSUE TITLE
Add this library as a third party lib on Clickhouse

### ISSUE THREAD

**Issue by Zarathustra2** [plausible/ecto_ch#62]
This lib should be listed here: https://clickhouse.com/docs/en/interfaces/third-party/client-libraries

**Comment by ruslandoga** [comment]
Do you think it's ready to be listed or should we battle-test it a bit more?

**Comment by Zarathustra2** [comment]
maybe the timezone issue is the only thing that is left to fix but that is one hell of a pesky bug.

**Comment by ruslandoga** [comment]
And maybe we can add it here as well: https://github.com/elixir-ecto/ecto#usage

**Comment by ruslandoga** [comment]
I've opened a PR to add ecto_ch to https://clickhouse.com/docs/en/interfaces/third-party/client-libraries:  https://github.com/ClickHouse/ClickHouse/pull/56622

**Comment by ruslandoga** [comment]
And I've also opened a PR to add ecto_ch to https://github.com/elixir-ecto/ecto#usage: https://github.com/elixir-ecto/ecto/pull/4313

**Comment by ruslandoga** [comment]
Closing as we've done out part. The rest is up to the maintainers to accept ecto_ch or not :)
