### ISSUE TITLE
Issue inserting data is throwing: DB::Exception

### ISSUE THREAD

**Issue by Zarathustra2** [plausible/ecto_ch#70]
I am getting the error ` (Ch.Error) Code: 32. DB::Exception: Attempt to read after eof: While executing BinaryRowInputFormat. (ATTEMPT_TO_READ_AFTER_EOF)` when I try to insert a struct into a table.

I have attempted to comment out all fields and just have a single field and try to insert only that but that also fails.

How would I go debugging it further?

**Comment by ruslandoga** [comment]
👋 @Zarathustra2 

What version of `ecto_ch` and `ch` are you using?

```console
$ cat mix.lock | grep ecto_ch
$ cat mix.lock | grep \"ch\"
```

What is the table definition? 

```sql
CREATE TABLE ... (...) ENGINE ...;
```

What is your Ecto schema?

```elixir
schema "..." do
  ...
end
```

What data are you inserting?

```elixir
Repo.insert(%...{value1: 1, value2: 2})
```

**Comment by Zarathustra2** [comment]
oh man @ruslandoga Just upgrade ch from 0.1.5 to 0.1.10 and the issue got fixed... ecto_ch was on 0.1.4 already.

Maybe we require minimum 0.1.10 ch for ecto_ch 0.1.4 ?

**Comment by ruslandoga** [comment]
Good call: https://github.com/plausible/ecto_ch/pull/71
