### ISSUE TITLE
Error trying to do rollback

### ISSUE THREAD

**Issue by daviaws** [plausible/ecto_ch#81]
I just made the migrations run, and its all fine, so I tried `mix ecto.rollback -n 11 -r Hermes.RepoClickhouse`
and boom
![image](https://github.com/plausible/ecto_ch/assets/12686471/b4406bca-37d2-475d-8790-97cd4d64c38a)

**Comment by ruslandoga** [comment]
👋 @daviaws 

By default `TinyLog` table engine is used for stored executed migrations:

```elixir
config :ecto_ch, default_table_engine: "TinyLog"
```

and TinyLog doesn't support deletions.

Related: https://github.com/plausible/ecto_ch/issues/47
