### ISSUE TITLE
(Ecto.QueryError) unknown or ambiguous (for ClickHouse) Ecto type :utc_datetime in query

### ISSUE THREAD

**Issue by daviaws** [plausible/ecto_ch#87]
Start at is an **utc_datetime** field on postgres schema.
**field :start_at, :utc_datetime**

Start at is a **DateTime** field on clickhouse schema.
**field :start_at, Ch, type: "DateTime"**

It is queried in this way:
```
      start_at:
        date_trunc(
          v.start_at |> convert_timezone("Z", "America/Bahia"),
          ^grouped_by
        )
        |> type(:utc_datetime)
        |> selected_as(:new_start_at)
``` 

Gives me the error:
(Ecto.QueryError) unknown or ambiguous (for ClickHouse) Ecto type :utc_datetime in query
![image](https://github.com/plausible/ecto_ch/assets/12686471/dbc71009-4e1f-4d98-a877-e26a5bcac347)

**Comment by ruslandoga** [comment]
👋 @daviaws 

Can you please explain why this is a problem a bit more?

**Comment by daviaws** [comment]
I thought it would just change the Schema/Repo and no more changes to my ecto query API work.
But I bumped on this error, not sure why.

**Comment by ruslandoga** [comment]
If you are wondering where the error comes from, it's `|> type(:utc_datetime)`, the since ClickHouse doesn't have a notion of UTC datetimes, this adapter is raising.

**Comment by ruslandoga** [comment]
> I thought it would be just change the Schema/Repo and no more changes to my ecto query API to work.

I think this is a wrong assumption. Not all queries would work the same / be supported in different adapters.

**Comment by daviaws** [comment]
What is the right one?
And there is no way to have a mapping?

**Comment by ruslandoga** [comment]
> What is the right one?

The right assumption? The opposite of the wrong one :)

> And there is no way to have a mapping?

Mapping of adapters or datetimes?

**Comment by daviaws** [comment]
> The right assumption? 
for type(:utc_datetime) to work on ecto_ch/ch/clickhouse :D
should it be **type("DateTime")**?

> Mapping of adapters or datetimes?
Same as before **type(:utc_datetime)**

And thank you for your readiness, you're so quick to answer!

**Comment by ruslandoga** [comment]
Looking [at the code for this part,](https://github.com/plausible/ecto_ch/blob/0c3e3bcf21a9b58c20776c54879168f5dd273d44/lib/ecto/adapters/clickhouse/connection.ex#L878-L894) I think it might be possible to support `utc_datetime` here.

**Comment by ruslandoga** [comment]
> should it be type("DateTime")?

Something like this would probably work:

```elixir
@datetime Ecto.ParametirizedType.init(Ch, type: "DateTime")

def some_function do
  from "table", where: type(^1, ^@datetime)
end
```

**Comment by daviaws** [comment]
> ```elixir
> @datetime Ecto.ParametirizedType.init(Ch, type: "DateTime")
> ```

typo: Ecto.ParameterizedType.init

Just the typed solution gives me:
(Ecto.Query.CompileError) type/2 expects an alias, atom, initialized parameterized type or source.field as second argument, got: `@datetime`

**Comment by daviaws** [comment]
New error :thinking: :thought_balloon: 
```
     ** (Ecto.QueryError) unknown or ambiguous (for ClickHouse) Ecto type :float in query:
```

**Comment by ruslandoga** [comment]
`type(..., :float)` is not supported either for the same reason, which float to you want to cast to, Float32 or Float64?

**Comment by ruslandoga** [comment]
If possible, please post the full error message. It should include the failing Ecto query.

**Comment by daviaws** [comment]
@datetime Ecto.ParameterizedType.init(Ch, type: "DateTime")
# or @datetime Ecto.ParameterizedType.init(Ch, type: "DateTime('UTC')")
```
      start_at:
        date_trunc(
          v.start_at |> convert_timezone("Z", "America/Bahia"),
          ^grouped_by
        )
        |> type(^@datetime)
        |> selected_as(:new_start_at)
```

Gives:      **** (Ecto.QueryError) unknown or ambiguous (for ClickHouse) Ecto type :float in query:**


If I just remove the cast **type**.
```
      start_at:
        date_trunc(
          v.start_at |> convert_timezone("Z", "America/Bahia"),
          ^grouped_by
        )
        |> selected_as(:new_start_at)
```
Gives:     **** (Ecto.QueryError) unknown or ambiguous (for ClickHouse) Ecto type :float in query:**

**Comment by daviaws** [comment]
Meanwhile I'm checking :thinking: 
https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#parsedatetimebesteffort

**Comment by ruslandoga** [comment]
`:float` casting probably comes from some other place in the query :)

**Comment by daviaws** [comment]
Right, so it worked I think. I commented the full query to isolate the problem and let it as

```
    VehicleSummaryReplicated
    |> select([v], %{
      vehicle_id: v.vehicle_id,
      start_at:
        date_trunc(
          v.start_at |> convert_timezone("Z", "America/Bahia"),
          ^grouped_by
        )
        |> type(^@datetime)
        |> selected_as(:new_start_at)
    })
   |> RepoClickhouse.all()
```

What comes next is :thinking: 

 ** (Ch.Error) Code: 62. DB::Exception: Syntax error: failed at position 69 ('AT'): AT TIME ZONE 'Z') AT TIME ZONE 'America/Bahia')) AS DateTime) AS "new_start_at" FROM "vehicle_summaries_replicated" AS v0. Expected one of: token, Dot, Comma, ClosingRoundBracket, OR, AND, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, end of query. (SYNTAX_ERROR) (version 23.6.1.1524 (official build))

**Comment by ruslandoga** [comment]
I think the error messages are reasonable. The problems seem to be with the queries. Would it be OK to close the issue?

**Comment by daviaws** [comment]
Yes, I think this is related to my macros.

Do you think you can support this solution?

https://github.com/plausible/ecto_ch/issues/87#issuecomment-1628658812

And thank you for your help :)

**Comment by ruslandoga** [comment]
> Do you think you can support this solution?
> https://github.com/plausible/ecto_ch/issues/87#issuecomment-1628658812

What solution?

**Comment by ruslandoga** [comment]
Ah, no. It's probably not going to be supported as it's still ambiguous what type the user wants: `DateTime` or `DateTime('UTC')`.

**Comment by daviaws** [comment]
> `type(..., :float)` is not supported for the same reason, ambiguity: do you want to cast to `Float32` or `Float64`?
> 
> More info: https://clickhouse.com/docs/en/sql-reference/data-types/float

But you know. This information is in my schema. The API can't just introspect over it?
