### ISSUE TITLE
(Ch.Error) Code: 376. DB::ParsingException: Cannot parse uuid

### ISSUE THREAD

**Issue by daviaws** [plausible/ecto_ch#90]
** (Ch.Error) Code: 376. DB::ParsingException: Cannot parse uuid <<204>>`Y<<160, 15>>,G#<<133, 179, 255, 183>>1<<26>>L"\a": while converting '<<204>>`Y<<160, 15>>,G#<<133, 179, 255, 183>>1<<26>>L"\a"' to UUID: While processing (driver_id IN ('<<204>>`Y<<160, 15>>,G#<<133, 179, 255, 183>>1<<26>>L"\a"')) AND 0 AND ((reported_at >= _CAST(1577836800, 'DateTime')) AND (reported_at <= _CAST(1577923199, 'DateTime'))). (CANNOT_PARSE_UUID) (version 23.6.1.1524 (official build))

```
query
|> where([e], e.vehicle_id in ^vehicle_ids)
|> where([e], e.geofence_id in ^geofence_ids)
```

Edit:
After some research, I see that this behavior just presents against geofence_id which is from type: "Nullable(UUID)" while vehicle_id is only UUID and seems to work fine.

**Comment by daviaws** [comment]
If we can find a quick solution... this is blocking me from launch code to production... :/

**Comment by ruslandoga** [comment]
👋 @daviaws 

I'll be able to look into this in about two hours. In the meanwhile, an easily reproducible example would be useful :)

**Comment by ruslandoga** [comment]
I've reproduced it for both `field :uuid, Ch, type: "UUID"` and `field :uuid, Ch, type: "Nullable(UUID)"`

**Comment by daviaws** [comment]
Thank you @ruslandoga I'll try in some minutes :)
